rem Tabler to x64dbg icons (png or svg) batch file converter
rem by mrfearless 2022
rem
rem * Download latest tabler icons zip: https://github.com/tabler/tabler-icons/releases
rem * Unzip tabler icons somewhere: C:\Icons\Tabler for example
rem * Edit this batch file. 
rem * Update source to point to folder where tabler svg or png icons are located
rem * Update dest (default is current folder where x64dbg-tabler.bat is located) to point to destination folder
rem * Choose extension (and thereby file type) to use:
rem * Comment out either set ext=svg or set ext=png and uncomment the other to use for extension.
rem * Open a command prompt (as admin ideally) and run this batch file to start the copy/conversion process
rem * x64dbg-tabler.bat

set source=C:\Icons\tabler-icons-1.74.0\icons
set dest=.
set ext=svg
rem set ext=png

rem copy /y ""%source%\ "%dest%\16bit-short.%ext%"
rem copy /y ""%source%\ "%dest%\16bit.%ext%"
rem copy /y ""%source%\ "%dest%\32bit-float.%ext%"
rem copy /y ""%source%\ "%dest%\32bit-long.%ext%"
copy /y "%source%\cpu.%ext%" "%dest%\32bit.%ext%"
rem copy /y ""%source%\ "%dest%\64bit-float.%ext%"
rem copy /y ""%source%\ "%dest%\64bit-long.%ext%"
copy /y "%source%\cpu-2.%ext%" "%dest%\64bit.%ext%"
rem copy /y "%source%\ "%dest%\80bit-float.%ext%"
rem copy /y "%source%\ "%dest%\80bit.%ext%"
copy /y "%source%\address-book.%ext%" "%dest%\address.%ext%"
copy /y "%source%\eyeglass.%ext%" "%dest%\analysis.%ext%"
copy /y "%source%\math-function.%ext%" "%dest%\analysis_single_function.%ext%"
copy /y "%source%\math-function.%ext%" "%dest%\analyzemodule.%ext%"
copy /y "%source%\paw.%ext%" "%dest%\animal-dog.%ext%"
copy /y "%source%\clear-all.%ext%" "%dest%\animatecommand.%ext%"
copy /y "%source%\chevrons-down.%ext%" "%dest%\animateinto.%ext%"
copy /y "%source%\chevrons-right.%ext%" "%dest%\animateover.%ext%"
rem copy /y "%source%\ "%dest%\arguments.%ext%"
copy /y "%source%\refresh-dot.%ext%" "%dest%\arrow-restart.%ext%"
copy /y "%source%\arrow-bar-to-right.%ext%" "%dest%\arrow-run-cursor.%ext%"
copy /y "%source%\player-play.%ext%" "%dest%\arrow-run.%ext%"
copy /y "%source%\player-skip-forward.%ext%" "%dest%\arrow-skip.%ext%"
rem copy /y "%source%\ "%dest%\arrow-small-down.%ext%"
rem copy /y "%source%\ "%dest%\arrow-small-up.%ext%"
copy /y "%source%\arrow-autofit-down.%ext%" "%dest%\arrow-step-into.%ext%"
copy /y "%source%\arrow-autofit-right.%ext%" "%dest%\arrow-step-over.%ext%"
copy /y "%source%\arrow-bar-to-up.%ext%" "%dest%\arrow-step-rtr.%ext%"
copy /y "%source%\arrow-top-circle.%ext%" "%dest%\arrow-threads.%ext%"
copy /y "%source%\a-b.%ext%" "%dest%\ascii-extended.%ext%"
copy /y "%source%\alphabet-latin.%ext%" "%dest%\ascii.%ext%"
copy /y "%source%\heart-plus.%ext%" "%dest%\attach.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_copy.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_edit.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_fill.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_fill_nop.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_paste.%ext%"
copy /y "%source%\binary.%ext%" "%dest%\binary_paste_ignoresize.%ext%"
copy /y "%source%\file-database.%ext%" "%dest%\binary_save.%ext%"
rem copy /y "%source%\ "%dest%\bit.%ext%"
copy /y "%source%\bookmark.%ext%" "%dest%\bookmark.%ext%"
copy /y "%source%\bookmark.%ext%" "%dest%\bookmark_toggle.%ext%"
copy /y "%source%\bookmarks.%ext%" "%dest%\bookmarks.%ext%"
copy /y "%source%\step-into.%ext%" "%dest%\bottom.%ext%"
rem copy /y "%source%\ "%dest%\branchpreview.%ext%"
copy /y "%source%\circle-dot.%ext%" "%dest%\breakpoint.%ext%"
copy /y "%source%\circle-dot.%ext%" "%dest%\breakpoint_access.%ext%"
copy /y "%source%\circle-dot.%ext%" "%dest%\breakpoint_add.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_byte.%ext%"
copy /y "%source%\circle-x.%ext%" "%dest%\breakpoint_disable.%ext%"
copy /y "%source%\circle-x.%ext%" "%dest%\breakpoint_disable_all.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_dword.%ext%"
copy /y "%source%\circle-rectangle.%ext%" "%dest%\breakpoint_edit.%ext%"
copy /y "%source%\circle-rectangle.%ext%" "%dest%\breakpoint_edit_alt.%ext%"
copy /y "%source%\circle-rectangle.%ext%" "%dest%\breakpoint_editcaret.%ext%"
copy /y "%source%\circle-check.%ext%" "%dest%\breakpoint_enable.%ext%"
copy /y "%source%\circle-check.%ext%" "%dest%\breakpoint_enable_all.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_exception_add.%ext%"
copy /y "%source%\circle-triangle.%ext%" "%dest%\breakpoint_execute.%ext%"
copy /y "%source%\circle-triangle.%ext%" "%dest%\breakpoint_execute_slot1.%ext%"
copy /y "%source%\circle-triangle.%ext%" "%dest%\breakpoint_execute_slot2.%ext%"
copy /y "%source%\circle-triangle.%ext%" "%dest%\breakpoint_execute_slot3.%ext%"
copy /y "%source%\circle-triangle.%ext%" "%dest%\breakpoint_execute_slot4.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_access.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_execute.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_read.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_restore_on_hit.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_singleshoot.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_memory_write.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_module_add.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_qword.%ext%"
copy /y "%source%\circle.%ext%" "%dest%\breakpoint_remove.%ext%"
copy /y "%source%\circle-off.%ext%" "%dest%\breakpoint_remove_all.%ext%"
copy /y "%source%\circle-off.%ext%" "%dest%\breakpoint_remove_all_commands.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_reset_hitcount.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_seton_all_commands.%ext%"
copy /y "%source%\circle-dashed.%ext%" "%dest%\breakpoint_settings.%ext%"
copy /y "%source%\circle-dot.%ext%" "%dest%\breakpoint_toggle.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_word.%ext%"
rem copy /y "%source%\ "%dest%\breakpoint_write.%ext%"
copy /y "%source%\devices-pc.%ext%" "%dest%\browseinexplorer.%ext%"
copy /y "%source%\bug.%ext%" "%dest%\bug-report.%ext%"
copy /y "%source%\bug.%ext%" "%dest%\bug.%ext%"
rem copy /y "%source%\ "%dest%\byte.%ext%"
copy /y "%source%\calculator.%ext%" "%dest%\calculator.%ext%"
copy /y "%source%\direction-sign.%ext%" "%dest%\call.%ext%"
copy /y "%source%\stack-pop.%ext%" "%dest%\callstack.%ext%"
copy /y "%source%\north-star.%ext%" "%dest%\cbp.%ext%"
rem copy /y "%source%\ "%dest%\change-view.%ext%"
copy /y "%source%\terminal-2.%ext%" "%dest%\changeargs.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas1.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas2.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas3.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas4.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas5.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas6.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas7.%ext%"
copy /y "%source%\christmas-tree.%ext%" "%dest%\christmas8.%ext%"
rem copy /y "%source%\ "%dest%\close-all-tabs.%ext%"
rem copy /y "%source%\ "%dest%\codepage.%ext%"
copy /y "%source%\color-picker.%ext%" "%dest%\color-swatches.%ext%"
copy /y "%source%\message-code.%ext%" "%dest%\comment.%ext%"
copy /y "%source%\messages.%ext%" "%dest%\comments.%ext%"
copy /y "%source%\sort-descending.%ext%" "%dest%\compile-error.%ext%"
copy /y "%source%\sort-descending.%ext%" "%dest%\compile-warning.%ext%"
copy /y "%source%\sort-descending-2.%ext%" "%dest%\compile.%ext%"
copy /y "%source%\door-exit.%ext%" "%dest%\control-exit.%ext%"
copy /y "%source%\player-pause.%ext%" "%dest%\control-pause.%ext%"
copy /y "%source%\square-dot.%ext%" "%dest%\control-stop.%ext%"
copy /y "%source%\copy.%ext%" "%dest%\copy-alt.%ext%"
copy /y "%source%\copy.%ext%" "%dest%\copy.%ext%"
copy /y "%source%\address-book.%ext%" "%dest%\copy_address.%ext%"
copy /y "%source%\layout-bottombar.%ext%" "%dest%\copy_cropped_table.%ext%"
copy /y "%source%\layout-board-split.%ext%" "%dest%\copy_disassembly.%ext%"
copy /y "%source%\table.%ext%" "%dest%\copy_full_table.%ext%"
copy /y "%source%\layout-2.%ext%" "%dest%\copy_item.%ext%"
copy /y "%source%\layout.%ext%" "%dest%\copy_selection.%ext%"
copy /y "%source%\layout-off.%ext%" "%dest%\copy_selection_no_bytes.%ext%"
copy /y "%source%\layout-navbar.%ext%" "%dest%\copy_table_line.%ext%"
rem copy /y "%source%\ "%dest%\copyfilepath.%ext%"
copy /y "%source%\database-off.%ext%" "%dest%\crash_dump.%ext%"
copy /y "%source%\arrow-top-circle.%ext%" "%dest%\createthread.%ext%"
rem copy /y "%source%\ "%dest%\css.%ext%"
copy /y "%source%\database.%ext%" "%dest%\data-copy.%ext%"
copy /y "%source%\database-export.%ext%" "%dest%\database-export.%ext%"
copy /y "%source%\database-import.%ext%" "%dest%\database-import.%ext%"
copy /y "%source%\heart-minus.%ext%" "%dest%\detach.%ext%"
rem copy /y "%source%\ "%dest%\disable.%ext%"
copy /y "%source%\file-digit.%ext%" "%dest%\document-binary.%ext%"
copy /y "%source%\currency-bitcoin.%ext%" "%dest%\donate.%ext%"
copy /y "%source%\qrcode.%ext%" "%dest%\donation_qr.%ext%"
copy /y "%source%\3d-rotate.%ext%" "%dest%\download_symbols.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\dump.%ext%"
rem copy /y "%source%\ "%dest%\dword.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter1.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter2.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter3.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter4.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter5.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter6.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter7.%ext%"
copy /y "%source%\egg.%ext%" "%dest%\easter8.%ext%"
copy /y "%source%\file-pencil.%ext%" "%dest%\edit-script.%ext%"
rem copy /y "%source%\ "%dest%\enable.%ext%"
copy /y "%source%\north-star.%ext%" "%dest%\entrypoint.%ext%"
copy /y "%source%\eraser.%ext%" "%dest%\eraser.%ext%"
copy /y "%source%\alert-triangle.%ext%" "%dest%\exclamation.%ext%"
copy /y "%source%\message-circle.%ext%" "%dest%\faq.%ext%"
rem copy /y "%source%\ "%dest%\fatal-error.%ext%"
copy /y "%source%\file-digit.%ext%" "%dest%\fileoffset.%ext%"
copy /y "%source%\scan-eye.%ext%" "%dest%\find.%ext%"
rem copy /y "%source%\ "%dest%\fit.%ext%"
rem copy /y "%source%\ "%dest%\float.%ext%"
copy /y "%source%\file-import.%ext%" "%dest%\folder-horizontal-open.%ext%"
copy /y "%source%\north-star.%ext%" "%dest%\follow_entrypoint.%ext%"
copy /y "%source%\cpu-2.%ext%" "%dest%\follow_in_cpu.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump1.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump2.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump3.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump4.%ext%"
copy /y "%source%\truck.%ext%" "%dest%\follow_in_dump5.%ext%"
rem copy /y "%source%\ "%dest%\freeze.%ext%"
copy /y "%source%\brackets-contain-end.%ext%" "%dest%\functionend.%ext%"
copy /y "%source%\brackets-contain.%ext%" "%dest%\functions.%ext%"
copy /y "%source%\brackets-contain-start.%ext%" "%dest%\functionstart.%ext%"
copy /y "%source%\current-location.%ext%" "%dest%\geolocation-goto.%ext%"
copy /y "%source%\elevator.%ext%" "%dest%\goto.%ext%"
copy /y "%source%\hierarchy-2.%ext%" "%dest%\graph.%ext%"
copy /y "%source%\zoom-question.%ext%" "%dest%\guid.%ext%"
copy /y "%source%\components.%ext%" "%dest%\handles.%ext%"
copy /y "%source%\help.%ext%" "%dest%\help.%ext%"
copy /y "%source%\info-circle.%ext%" "%dest%\helpbrief.%ext%"
copy /y "%source%\info-circle.%ext%" "%dest%\helpmnemonic.%ext%"
rem copy /y "%source%\ "%dest%\hex.%ext%"
copy /y "%source%\eye-off.%ext%" "%dest%\hide-debugger.%ext%"
copy /y "%source%\layers-off.%ext%" "%dest%\hidetab.%ext%"
copy /y "%source%\highlight.%ext%" "%dest%\highlight.%ext%"
copy /y "%source%\photo.%ext%" "%dest%\image.%ext%"
rem copy /y "%source%\ "%dest%\import.%ext%"
rem copy /y "%source%\ "%dest%\importsettings.%ext%"
copy /y "%source%\info-square.%ext%" "%dest%\information.%ext%"
copy /y "%source%\file-settings.%ext%" "%dest%\initscript.%ext%"
rem copy /y "%source%\ "%dest%\integer.%ext%"
copy /y "%source%\tag.%ext%" "%dest%\label.%ext%"
copy /y "%source%\tags.%ext%" "%dest%\labels.%ext%"
copy /y "%source%\template.%ext%" "%dest%\layout.%ext%"
copy /y "%source%\box.%ext%" "%dest%\lib.%ext%"
copy /y "%source%\package-off.%ext%" "%dest%\lib_free.%ext%"
copy /y "%source%\packge-import.%ext%" "%dest%\lib_load.%ext%"
copy /y "%source%\file-symlink.%ext%" "%dest%\load-script.%ext%"
copy /y "%source%\variable.%ext%" "%dest%\localvars.%ext%"
copy /y "%source%\lock.%ext%" "%dest%\lock.%ext%"
copy /y "%source%\license.%ext%" "%dest%\log.%ext%"
copy /y "%source%\confetti.%ext%" "%dest%\markasparty.%ext%"
copy /y "%source%\device-analytics.%ext%" "%dest%\markassystem.%ext%"
copy /y "%source%\user-check.%ext%" "%dest%\markasuser.%ext%"
rem copy /y "%source%\ "%dest%\medium.%ext%"
copy /y "%source%\box-margin.%ext%" "%dest%\memmap_alloc_memory.%ext%"
copy /y "%source%\file-dots.%ext%" "%dest%\memmap_dump_memory_to_file.%ext%"
copy /y "%source%\container.%ext%" "%dest%\memmap_find_address_page.%ext%"
copy /y "%source%\border-none.%ext%" "%dest%\memmap_free_memory.%ext%"
copy /y "%source%\border-outer.%ext%" "%dest%\memmap_memory_breakpoint.%ext%"
copy /y "%source%\box-padding.%ext%" "%dest%\memmap_set_page_memory_rights.%ext%"
copy /y "%source%\container.%ext%" "%dest%\memory-map.%ext%"
copy /y "%source%\pencil.%ext%" "%dest%\modify.%ext%"
copy /y "%source%\zoom-question.%ext%" "%dest%\names.%ext%"
rem copy /y "%source%\ "%dest%\narrow.%ext%"
copy /y "%source%\asterisk.%ext%" "%dest%\neworigin.%ext%"
copy /y "%source%\layout-sidebar-left-expand.%ext%" "%dest%\next.%ext%"
copy /y "%source%\layout-sidebar-right-collapse.%ext%" "%dest%\nextref.%ext%"
copy /y "%source%\notes.%ext%" "%dest%\notes.%ext%"
copy /y "%source%\bandage.%ext%" "%dest%\patch.%ext%"
copy /y "%source%\package.%ext%" "%dest%\pdb.%ext%"
copy /y "%source%\package.%ext%" "%dest%\pdb_alt.%ext%"
copy /y "%source%\api-app.%ext%" "%dest%\plugin.%ext%"
copy /y "%source%\layout-sidebar-left-collapse.%ext%" "%dest%\previous.%ext%"
copy /y "%source%\layout-sidebar-right-expand.%ext%" "%dest%\prevref.%ext%"
copy /y "%source%\cpu-2.%ext%" "%dest%\processor-cpu.%ext%"
copy /y "%source%\cpu.%ext%" "%dest%\processor32.%ext%"
copy /y "%source%\cpu-2.%ext%" "%dest%\processor64.%ext%"
copy /y "%source%\question.%ext%" "%dest%\question.%ext%"
rem copy /y "%source%\ "%dest%\qword.%ext%"
copy /y "%source%\list.%ext%" "%dest%\recentfiles.%ext%"
rem copy /y "%source%\ "%dest%\register_dec.%ext%"
copy /y "%source%\credit-card.%ext%" "%dest%\register_edit.%ext%"
rem copy /y "%source%\ "%dest%\register_inc.%ext%"
rem copy /y "%source%\ "%dest%\register_one.%ext%"
rem copy /y "%source%\ "%dest%\register_toggle.%ext%"
rem copy /y "%source%\ "%dest%\register_zero.%ext%"
rem copy /y "%source%\ "%dest%\remove_analysis_from_module.%ext%"
rem copy /y "%source%\ "%dest%\remove_analysis_from_selection.%ext%"
rem copy /y "%source%\ "%dest%\removestruct.%ext%"
copy /y "%source%\arrow-guide.%ext%" "%dest%\runtouser.%ext%"
copy /y "%source%\file-power.%ext%" "%dest%\script-code.%ext%"
copy /y "%source%\file-alert.%ext%" "%dest%\script-error.%ext%"
rem copy /y "%source%\ "%dest%\scylla.%ext%"
copy /y "%source%\search.%ext%" "%dest%\search-for.%ext%"
copy /y "%source%\search.%ext%" "%dest%\search.%ext%"
copy /y "%source%\search.%ext%" "%dest%\search_all_modules.%ext%"
copy /y "%source%\zoom-pan.%ext%" "%dest%\search_current_module.%ext%"
copy /y "%source%\zoom-pan.%ext%" "%dest%\search_current_region.%ext%"
copy /y "%source%\zoom-check.%ext%" "%dest%\search_for_command.%ext%"
copy /y "%source%\zoom-check.%ext%" "%dest%\search_for_constant.%ext%"
copy /y "%source%\zoom-question.%ext%" "%dest%\search_for_pattern.%ext%"
copy /y "%source%\zoom-money.%ext%" "%dest%\search_for_string.%ext%"
copy /y "%source%\link.%ext%" "%dest%\seh-chain.%ext%"
copy /y "%source%\settings.%ext%" "%dest%\settings.%ext%"
rem copy /y "%source%\ "%dest%\shortcut.%ext%"
rem copy /y "%source%\ "%dest%\simdmode.%ext%"
copy /y "%source%\code.%ext%" "%dest%\source.%ext%"
copy /y "%source%\file-code.%ext%" "%dest%\source_show_in_folder.%ext%"
copy /y "%source%\stack.%ext%" "%dest%\stack.%ext%"
copy /y "%source%\star.%ext%" "%dest%\star.%ext%"
copy /y "%source%\hash.%ext%" "%dest%\strings.%ext%"
copy /y "%source%\border-all.%ext%" "%dest%\struct.%ext%"
copy /y "%source%\border-all.%ext%" "%dest%\structaddr.%ext%"
rem copy /y "%source%\ "%dest%\summary.%ext%"
rem copy /y "%source%\ "%dest%\sync.%ext%"
copy /y "%source%\prompt.%ext%" "%dest%\terminal-command.%ext%"
copy /y "%source%\comet.%ext%" "%dest%\themes.%ext%"
copy /y "%source%\arrow-top-circle.%ext%" "%dest%\thread-entry.%ext%"
copy /y "%source%\git-pull-request-closed.%ext%" "%dest%\thread-kill.%ext%"
copy /y "%source%\git-pull-request-draft.%ext%" "%dest%\thread-pause.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-above-normal.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-below-normal.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-highest.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-idle.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-lowest.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-normal.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-priority-timecritical.%ext%"
copy /y "%source%\git-branch.%ext%" "%dest%\thread-resume.%ext%"
copy /y "%source%\shape-3.%ext%" "%dest%\thread-setname.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-setpriority.%ext%"
copy /y "%source%\git-merge.%ext%" "%dest%\thread-setpriority_alt.%ext%"
copy /y "%source%\git-pull-request.%ext%" "%dest%\thread-switch.%ext%"
copy /y "%source%\step-out.%ext%" "%dest%\top.%ext%"
rem copy /y "%source%\ "%dest%\topmost.%ext%"
rem copy /y "%source%\ "%dest%\trace.%ext%"
copy /y "%source%\arrow-big-down-lines.%ext%" "%dest%\traceinto.%ext%"
copy /y "%source%\arrow-big-right-lines.%ext%" "%dest%\traceover.%ext%"
rem copy /y "%source%\ "%dest%\treat_from_selection_as.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_ascii.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_byte.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_cmd.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_double.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_dword.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_float.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_fword.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_longdouble.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_mmword.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_oword.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_qword.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_tbyte.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_unicode.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_word.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_xmm.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_as_ymm.%ext%"
rem copy /y "%source%\ "%dest%\treat_selection_head_as.%ext%"
copy /y "%source%\shield-checkered.%ext%" "%dest%\uac.%ext%"
rem copy /y "%source%\ "%dest%\ui-combo-box-edit.%ext%"
copy /y "%source%\player-skip-back.%ext%" "%dest%\undo.%ext%"
copy /y "%source%\alphabet-cyrillic.%ext%" "%dest%\unicode.%ext%"
copy /y "%source%\world-download.%ext%" "%dest%\update.%ext%"
copy /y "%source%\variable.%ext%" "%dest%\variables.%ext%"
rem copy /y "%source%\ "%dest%\virtual.%ext%"
rem copy /y "%source%\ "%dest%\visitstruct.%ext%"
rem copy /y "%source%\ "%dest%\wide.%ext%"
rem copy /y "%source%\ "%dest%\win-help.%ext%"
rem copy /y "%source%\ "%dest%\word.%ext%"
rem copy /y "%source%\ "%dest%\xmm.%ext%"
copy /y "%source%\zoom-code.%ext%" "%dest%\xrefs.%ext%"
rem copy /y "%source%\ "%dest%\yara.%ext%"
rem copy /y "%source%\ "%dest%\ymm.%ext%"
rem copy /y "%source%\ "%dest%\zmm.%ext%"
copy /y "%source%\zoom-in.%ext%"  "%dest%\zoom.%ext%" 